PROJECT_ROOT=".../your/path/to/DeepDxSearch"
export PYTHONUNBUFFERED=1
export HYDRA_FULL_ERROR=1
export CUDA_VISIBLE_DEVICES=4,5,6,7
# 将src目录添加到PYTHONPATH
export PYTHONPATH="${PROJECT_ROOT}/src:${PYTHONPATH}"

NGPUS=4
MODEL_PARALLEL=4
MATCH_TOP_N=20
LOOKUP_MAX_N=10
PROJECT_NAME=DeepDxSearch
EXPERIMENT_NAME=DiagRLEvalRareAll      #DiagRLGeneralFreeBaichuanM232B  #DiagRLGeneralFreeMedGemma27B
TRAIN_FILES=.../your/path/to/DeepDxSearch/data/train_data.parquet
TEST_FILES=.../your/path/to/DeepDxSearch/data/val_data.parquet
TRAIN_BATCH_SIZE=64
VAL_BATCH_SIZE=5000
PROMPT_KEY=input
MAX_PROMPT_LENGTH=3072
MAX_RESPONSE_LENGTH=10240     #8192
MATCH_SOURCE=.../your/path/to/DeepDxSearch/src/match/match_source_rare.json
LOOKUP_SOURCE=.../your/path/to/DeepDxSearch/src/lookup/DataProcess/disease_guidelines.json
SEARCH_SUMMARIZE=True
PMC_PORT=8000
WIKI_PORT=8001
BOOK_PORT=8002
SGL_PORT=38666
PROMPT_TEMPLATE_NAME=deep_dx_search_template_sys
APPLY_CHAT=True
ACTOR_MODEL_PATH=/mnt/vision_user/huggingface/medgemma-27b-text-it          #/mnt/vision_user/huggingface/Qwen2.5-32B-Instruct  #/mnt/vision_user/huggingface/medgemma-27b-text-it  #/mnt/vision_user/huggingface/Baichuan-M2-32B
PPO_MINI_BATCH_SIZE=16
PPO_MICRO_BATCH_SIZE=2
REWARD_MANAGER=deep_dx_search
TOTAL_TRAINING_STEPS=1000

/mnt/vision_user/yibinyan/miniconda3/envs/verl/bin/python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files="$TRAIN_FILES" \
    data.val_files="$TEST_FILES" \
    data.prompt_key=${PROMPT_KEY} \
    data.train_batch_size=${TRAIN_BATCH_SIZE} \
    data.val_batch_size=${VAL_BATCH_SIZE} \
    data.max_prompt_length=${MAX_PROMPT_LENGTH} \
    data.max_response_length=${MAX_RESPONSE_LENGTH} \
    data.apply_chat_template_kwargs.apply_chat=${APPLY_CHAT} \
    data.apply_chat_template_kwargs.prompt_template_name=${PROMPT_TEMPLATE_NAME} \
    data.apply_chat_template_kwargs.thinking_mode=off \
    data.filter_overlong_prompts=True \
    data.truncation='error' \
    data.shuffle=False \
    actor_rollout_ref.model.path=${ACTOR_MODEL_PATH} \
    actor_rollout_ref.model.lora_rank=32 \
    actor_rollout_ref.model.lora_alpha=16 \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.0 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=${PPO_MINI_BATCH_SIZE} \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=${PPO_MICRO_BATCH_SIZE} \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.0005 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.match_source=${MATCH_SOURCE} \
    actor_rollout_ref.rollout.match_top_n=${MATCH_TOP_N} \
    actor_rollout_ref.rollout.lookup_source=${LOOKUP_SOURCE} \
    actor_rollout_ref.rollout.lookup_max_n=${LOOKUP_MAX_N} \
    actor_rollout_ref.rollout.search_summarize=${SEARCH_SUMMARIZE} \
    actor_rollout_ref.rollout.search_ports.pmc_port=${PMC_PORT} \
    actor_rollout_ref.rollout.search_ports.wiki_port=${WIKI_PORT} \
    actor_rollout_ref.rollout.search_ports.book_port=${BOOK_PORT} \
    actor_rollout_ref.rollout.search_ports.sgl_port=${SGL_PORT} \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=${PPO_MICRO_BATCH_SIZE} \
    actor_rollout_ref.rollout.tensor_model_parallel_size=${MODEL_PARALLEL} \
    actor_rollout_ref.rollout.name=vllm_with_deep_dx_search \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.rollout.n=5 \
    actor_rollout_ref.rollout.load_format=safetensors \
    actor_rollout_ref.rollout.layered_summon=True \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=${PPO_MICRO_BATCH_SIZE} \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    reward_model.reward_manager=${REWARD_MANAGER} \
    algorithm.use_kl_in_reward=False \
    algorithm.kl_ctrl.kl_coef=0.0005 \
    trainer.val_before_train=True \
    trainer.critic_warmup=0 \
    trainer.logger='["console"]' \
    trainer.project_name=${PROJECT_NAME} \
    trainer.experiment_name=${EXPERIMENT_NAME} \
    trainer.n_gpus_per_node=${NGPUS} \
    trainer.nnodes=1 \
    trainer.save_freq=30 \
    trainer.test_freq=30 \
    trainer.rollout_save_path=.../your/path/to/DeepDxSearch/scripts/train/checkpoints/${PROJECT_NAME}/${EXPERIMENT_NAME}/outputs \
    trainer.total_epochs=15 2>&1 | tee verl_demo_${EXPERIMENT_NAME}.log